/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleVehiclesIndexRouteImport } from './routes/console/vehicles/index'
import { Route as ConsoleSupportIndexRouteImport } from './routes/console/support/index'
import { Route as ConsoleSettingsIndexRouteImport } from './routes/console/settings/index'
import { Route as ConsoleRidesIndexRouteImport } from './routes/console/rides/index'
import { Route as ConsoleRidersIndexRouteImport } from './routes/console/riders/index'
import { Route as ConsolePaymentsIndexRouteImport } from './routes/console/payments/index'
import { Route as ConsoleDriversIndexRouteImport } from './routes/console/drivers/index'
import { Route as ConsoleSupportReportsIndexRouteImport } from './routes/console/support/reports/index'
import { Route as ConsoleSupportRatingsIndexRouteImport } from './routes/console/support/ratings/index'
import { Route as ConsoleSettingsPricingIndexRouteImport } from './routes/console/settings/pricing/index'
import { Route as ConsoleSettingsNotificationsIndexRouteImport } from './routes/console/settings/notifications/index'
import { Route as ConsoleSettingsLocationsIndexRouteImport } from './routes/console/settings/locations/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleVehiclesIndexRoute = ConsoleVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSupportIndexRoute = ConsoleSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsIndexRoute = ConsoleSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleRidesIndexRoute = ConsoleRidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleRidersIndexRoute = ConsoleRidersIndexRouteImport.update({
  id: '/riders/',
  path: '/riders/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsolePaymentsIndexRoute = ConsolePaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDriversIndexRoute = ConsoleDriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSupportReportsIndexRoute =
  ConsoleSupportReportsIndexRouteImport.update({
    id: '/support/reports/',
    path: '/support/reports/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleSupportRatingsIndexRoute =
  ConsoleSupportRatingsIndexRouteImport.update({
    id: '/support/ratings/',
    path: '/support/ratings/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleSettingsPricingIndexRoute =
  ConsoleSettingsPricingIndexRouteImport.update({
    id: '/settings/pricing/',
    path: '/settings/pricing/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleSettingsNotificationsIndexRoute =
  ConsoleSettingsNotificationsIndexRouteImport.update({
    id: '/settings/notifications/',
    path: '/settings/notifications/',
    getParentRoute: () => ConsoleRoute,
  } as any)
const ConsoleSettingsLocationsIndexRoute =
  ConsoleSettingsLocationsIndexRouteImport.update({
    id: '/settings/locations/',
    path: '/settings/locations/',
    getParentRoute: () => ConsoleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/drivers/': typeof ConsoleDriversIndexRoute
  '/console/payments/': typeof ConsolePaymentsIndexRoute
  '/console/riders/': typeof ConsoleRidersIndexRoute
  '/console/rides/': typeof ConsoleRidesIndexRoute
  '/console/settings/': typeof ConsoleSettingsIndexRoute
  '/console/support/': typeof ConsoleSupportIndexRoute
  '/console/vehicles/': typeof ConsoleVehiclesIndexRoute
  '/console/settings/locations/': typeof ConsoleSettingsLocationsIndexRoute
  '/console/settings/notifications/': typeof ConsoleSettingsNotificationsIndexRoute
  '/console/settings/pricing/': typeof ConsoleSettingsPricingIndexRoute
  '/console/support/ratings/': typeof ConsoleSupportRatingsIndexRoute
  '/console/support/reports/': typeof ConsoleSupportReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/console': typeof ConsoleIndexRoute
  '/console/drivers': typeof ConsoleDriversIndexRoute
  '/console/payments': typeof ConsolePaymentsIndexRoute
  '/console/riders': typeof ConsoleRidersIndexRoute
  '/console/rides': typeof ConsoleRidesIndexRoute
  '/console/settings': typeof ConsoleSettingsIndexRoute
  '/console/support': typeof ConsoleSupportIndexRoute
  '/console/vehicles': typeof ConsoleVehiclesIndexRoute
  '/console/settings/locations': typeof ConsoleSettingsLocationsIndexRoute
  '/console/settings/notifications': typeof ConsoleSettingsNotificationsIndexRoute
  '/console/settings/pricing': typeof ConsoleSettingsPricingIndexRoute
  '/console/support/ratings': typeof ConsoleSupportRatingsIndexRoute
  '/console/support/reports': typeof ConsoleSupportReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/login': typeof LoginRoute
  '/console/': typeof ConsoleIndexRoute
  '/console/drivers/': typeof ConsoleDriversIndexRoute
  '/console/payments/': typeof ConsolePaymentsIndexRoute
  '/console/riders/': typeof ConsoleRidersIndexRoute
  '/console/rides/': typeof ConsoleRidesIndexRoute
  '/console/settings/': typeof ConsoleSettingsIndexRoute
  '/console/support/': typeof ConsoleSupportIndexRoute
  '/console/vehicles/': typeof ConsoleVehiclesIndexRoute
  '/console/settings/locations/': typeof ConsoleSettingsLocationsIndexRoute
  '/console/settings/notifications/': typeof ConsoleSettingsNotificationsIndexRoute
  '/console/settings/pricing/': typeof ConsoleSettingsPricingIndexRoute
  '/console/support/ratings/': typeof ConsoleSupportRatingsIndexRoute
  '/console/support/reports/': typeof ConsoleSupportReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/login'
    | '/console/'
    | '/console/drivers/'
    | '/console/payments/'
    | '/console/riders/'
    | '/console/rides/'
    | '/console/settings/'
    | '/console/support/'
    | '/console/vehicles/'
    | '/console/settings/locations/'
    | '/console/settings/notifications/'
    | '/console/settings/pricing/'
    | '/console/support/ratings/'
    | '/console/support/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/console'
    | '/console/drivers'
    | '/console/payments'
    | '/console/riders'
    | '/console/rides'
    | '/console/settings'
    | '/console/support'
    | '/console/vehicles'
    | '/console/settings/locations'
    | '/console/settings/notifications'
    | '/console/settings/pricing'
    | '/console/support/ratings'
    | '/console/support/reports'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/login'
    | '/console/'
    | '/console/drivers/'
    | '/console/payments/'
    | '/console/riders/'
    | '/console/rides/'
    | '/console/settings/'
    | '/console/support/'
    | '/console/vehicles/'
    | '/console/settings/locations/'
    | '/console/settings/notifications/'
    | '/console/settings/pricing/'
    | '/console/support/ratings/'
    | '/console/support/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/vehicles/': {
      id: '/console/vehicles/'
      path: '/vehicles'
      fullPath: '/console/vehicles/'
      preLoaderRoute: typeof ConsoleVehiclesIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/support/': {
      id: '/console/support/'
      path: '/support'
      fullPath: '/console/support/'
      preLoaderRoute: typeof ConsoleSupportIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/': {
      id: '/console/settings/'
      path: '/settings'
      fullPath: '/console/settings/'
      preLoaderRoute: typeof ConsoleSettingsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/rides/': {
      id: '/console/rides/'
      path: '/rides'
      fullPath: '/console/rides/'
      preLoaderRoute: typeof ConsoleRidesIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/riders/': {
      id: '/console/riders/'
      path: '/riders'
      fullPath: '/console/riders/'
      preLoaderRoute: typeof ConsoleRidersIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/payments/': {
      id: '/console/payments/'
      path: '/payments'
      fullPath: '/console/payments/'
      preLoaderRoute: typeof ConsolePaymentsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/drivers/': {
      id: '/console/drivers/'
      path: '/drivers'
      fullPath: '/console/drivers/'
      preLoaderRoute: typeof ConsoleDriversIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/support/reports/': {
      id: '/console/support/reports/'
      path: '/support/reports'
      fullPath: '/console/support/reports/'
      preLoaderRoute: typeof ConsoleSupportReportsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/support/ratings/': {
      id: '/console/support/ratings/'
      path: '/support/ratings'
      fullPath: '/console/support/ratings/'
      preLoaderRoute: typeof ConsoleSupportRatingsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/pricing/': {
      id: '/console/settings/pricing/'
      path: '/settings/pricing'
      fullPath: '/console/settings/pricing/'
      preLoaderRoute: typeof ConsoleSettingsPricingIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/notifications/': {
      id: '/console/settings/notifications/'
      path: '/settings/notifications'
      fullPath: '/console/settings/notifications/'
      preLoaderRoute: typeof ConsoleSettingsNotificationsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings/locations/': {
      id: '/console/settings/locations/'
      path: '/settings/locations'
      fullPath: '/console/settings/locations/'
      preLoaderRoute: typeof ConsoleSettingsLocationsIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleDriversIndexRoute: typeof ConsoleDriversIndexRoute
  ConsolePaymentsIndexRoute: typeof ConsolePaymentsIndexRoute
  ConsoleRidersIndexRoute: typeof ConsoleRidersIndexRoute
  ConsoleRidesIndexRoute: typeof ConsoleRidesIndexRoute
  ConsoleSettingsIndexRoute: typeof ConsoleSettingsIndexRoute
  ConsoleSupportIndexRoute: typeof ConsoleSupportIndexRoute
  ConsoleVehiclesIndexRoute: typeof ConsoleVehiclesIndexRoute
  ConsoleSettingsLocationsIndexRoute: typeof ConsoleSettingsLocationsIndexRoute
  ConsoleSettingsNotificationsIndexRoute: typeof ConsoleSettingsNotificationsIndexRoute
  ConsoleSettingsPricingIndexRoute: typeof ConsoleSettingsPricingIndexRoute
  ConsoleSupportRatingsIndexRoute: typeof ConsoleSupportRatingsIndexRoute
  ConsoleSupportReportsIndexRoute: typeof ConsoleSupportReportsIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleDriversIndexRoute: ConsoleDriversIndexRoute,
  ConsolePaymentsIndexRoute: ConsolePaymentsIndexRoute,
  ConsoleRidersIndexRoute: ConsoleRidersIndexRoute,
  ConsoleRidesIndexRoute: ConsoleRidesIndexRoute,
  ConsoleSettingsIndexRoute: ConsoleSettingsIndexRoute,
  ConsoleSupportIndexRoute: ConsoleSupportIndexRoute,
  ConsoleVehiclesIndexRoute: ConsoleVehiclesIndexRoute,
  ConsoleSettingsLocationsIndexRoute: ConsoleSettingsLocationsIndexRoute,
  ConsoleSettingsNotificationsIndexRoute:
    ConsoleSettingsNotificationsIndexRoute,
  ConsoleSettingsPricingIndexRoute: ConsoleSettingsPricingIndexRoute,
  ConsoleSupportRatingsIndexRoute: ConsoleSupportRatingsIndexRoute,
  ConsoleSupportReportsIndexRoute: ConsoleSupportReportsIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
